# Generated by Django 5.2.1 on 2025-05-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_clothingitem_image_itemimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='size',
            new_name='sizes',
        ),
    ]
